---
- name: Remove markdown database
  postgresql_db:
    name: "{{ config.database.markdownsite.name }}"
    state: absent
  become_user: postgres
  become: true

- name: Create markdown database
  postgresql_db:
    name: "{{ config.database.markdownsite.name }}"
    owner: "{{ config.database.markdownsite.user }}"
    state: present
  become_user: postgres
  become: true

- name: Import the database
  shell: mds-manager dbc < /home/manager/markdownsite/Manager-DB/etc/schema.sql
  become: true
  become_user: manager

