---
- name: Drop markdown database
  postgresql_db:
    name: "{{ config.database.markdownsite.name }}"
    state: absent
  become_user: postgres
  become: true

- name: Drop minion database
  postgresql_db:
    name: "{{ config.database.minion.name }}"
    owner: "{{ config.database.minion.user }}"
    state: absent
  become_user: postgres
  become: true

- name: Create db user account for markdownsite
  postgresql_user:
    name: "{{ config.database.markdownsite.user }}"
    password: "{{ config.database.markdownsite.pass }}"
    state: present
  become_user: postgres
  become: true

- name: Create db user account for minion
  postgresql_user:
    name: "{{ config.database.minion.user }}"
    password: "{{ config.database.minion.pass }}"
    state: present
  become_user: postgres
  become: true

- name: Create markdown database
  postgresql_db:
    name: "{{ config.database.markdownsite.name }}"
    owner: "{{ config.database.markdownsite.user }}"
    state: present
  become_user: postgres
  become: true

- name: Create minion database
  postgresql_db:
    name: "{{ config.database.minion.name }}"
    owner: "{{ config.database.minion.user }}"
    state: present
  become_user: postgres
  become: true

- name: Import the database
  shell: mds-manager dbc < /home/manager/markdownsite/Panel-DB/etc/schema.sql > /home/manager/markdownsite/Panel-DB/etc/schema.log
  become: true
  become_user: manager

# Restart markdownsite.panel
- name: Start Markdownsite Panel
  service:
    name: markdownsite.panel
    state: started
    enabled: true
