---
- name: Update all packages to their latest version
  apt:
    name: "*"
    state: latest
    update_cache: yes

- name: Install packages
  apt:
    name: [
      'git',
      'build-essential',
      'cpanminus',
      'strace',
      'lighttpd',
      'libssl-dev',
      'libexpat1-dev',
      'libz-dev',
      'memcached',
      'vim',
      'libpq-dev',
    ]
    state: present

- name: Install /tmp/{{ config.versions.cgi }}
  copy:
    dest: /tmp/{{ config.versions.cgi }}
    src: "{{ role_path }}/files/builds/{{ config.versions.cgi }}"
    owner: root
    group: root
    mode: 0644

- name: Install MarkdownSite::CGI
  shell: cpanm {{ config.versions.cgi }}
  args:
    chdir: /tmp

- name: Install /etc/lighttpd/lighttpd.conf
  copy:
    dest: /etc/lighttpd/lighttpd.conf
    src: "{{ role_path }}/files/lighttpd.conf"
    owner: root
    group: root
    mode: 0644

- name: Install /etc/lighttpd/rewrite.lua
  copy:
    dest: /etc/lighttpd/rewrite.lua
    src: "{{ role_path }}/files/rewrite.lua"
    owner: root
    group: root
    mode: 0644

- name: Create /etc/lighttpd/conf.d
  file:
    state: directory
    path: /etc/lighttpd/conf.d
    owner: root
    group: root
    mode: 0755

- name: Setup /var/lib/cgi-bin/markdownsite.cgi 
  file:
    src: /usr/local/bin/markdownsite_cgi
    dest: /usr/lib/cgi-bin/markdownsite.cgi
    state: link

- name: Ensure /var/www/themes is populated.
  copy:
    src: "{{ role_path }}/files/themes/"
    dest: "/var/www/themes"
    mode: '0644'
    directory_mode: '0755'
    owner: 'www-data'
    group: 'www-data'

- name: Add ansible sshkey into root user
  lineinfile:
    path: /root/.ssh/authorized_keys
    line: "{{ config.serve.ansible_key }}"
    regexp: "{{ config.serve.ansible_key }}"
