---
- name: "Delete /etc/ansible/hosts."
  file:
    path: /etc/ansible/hosts
    state: absent

- name: "Create /etc/ansible/hosts."
  file:
    path: /etc/ansible/hosts
    state: touch
    owner: root
    group: root
    mode: 0644

- name: "Add hosts to /etc/ansible/hosts."
  lineinfile:
    path: /etc/ansible/hosts
    line: "{{ item }}"
    owner: root
    group: root
    mode: '0644'
  with_items: "{{ config.build.deploy_addresses }}"
