---
- name: Update all packages to their latest version
  apt:
    name: "*"
    state: latest
    update_cache: yes

- name: Install packages
  apt:
    name: [
      'git',
      'build-essential',
      'cpanminus',
      'libssl-dev',
      'libpq-dev',
      'libz-dev',
      'libexpat1-dev',
      'vim',
      'postgresql-client',
      'postgresql-contrib',
      'postgresql',
      'python3-psycopg2',
      'nginx',
      'certbot',
      'curl',
      'python3-certbot-nginx',
    ]
    state: present

- name: Install MarkdownSite::Manager::DB
  cpanm:
    name: "{{ config.pkg.manager_db }}"

- name: Install MarkdownSite::Panelr::DB
  cpanm:
    name: "{{ config.pkg.panel_db }}"

- name: Install MarkdownSite::Manager
  cpanm:
    name: "{{ config.pkg.manager }}"

- name: Install MarkdownSite::Panel
  cpanm:
    name: "{{ config.pkg.panel }}"

- name: Install /etc/markdownsite.yml
  template:
    src: "{{ role_path }}/templates/markdownsite.yml.j2"
    dest: /etc/markdownsite.yml
    owner: root
    group: root
    mode: 0644

- name: start postgresql
  service:
    name: postgresql
    state: started
    enabled: true

- name: Create db user account for markdownsite
  postgresql_user:
    name: "{{ config.database.markdownsite.user }}"
    password: "{{ config.database.markdownsite.pass }}"
    state: present
  become_user: postgres
  become: true

- name: Create db user account for minion
  postgresql_user:
    name: "{{ config.database.minion.user }}"
    password: "{{ config.database.minion.pass }}"
    state: present
  become_user: postgres
  become: true

- name: Create markdown database
  postgresql_db:
    name: "{{ config.database.markdownsite.name }}"
    owner: "{{ config.database.markdownsite.user }}"
    state: present
  become_user: postgres
  become: true

- name: Create minion database
  postgresql_db:
    name: "{{ config.database.minion.name }}"
    owner: "{{ config.database.minion.user }}"
    state: present
  become_user: postgres
  become: true

- name: Create manager user
  user:
    name: manager
    shell: /bin/bash
    comment: MarkdownSite Manager User Account

- name: Create ~manager/.ssh
  file:
    state: directory
    path: /home/manager/.ssh
    owner: manager
    group: manager
    mode: 0700

- name: Install ~manager/.ssh/id_rsa (for git clone)
  copy:
    dest: /home/manager/.ssh/id_rsa
    content: "{{ config.sshkeys.deploy_private }}"
    owner: manager
    group: manager
    mode: 0600

- name: Create ~manager/.ssh/authorized_keys from ~root
  copy:
    dest: /home/manager/.ssh/authorized_keys
    src: /root/.ssh/authorized_keys
    remote_src: true
    owner: manager
    group: manager
    mode: 0600

- name: Install markdownsite.panel.service file.
  copy:
    dest: /etc/systemd/system/markdownsite.panel.service
    src: "{{ role_path }}/files/markdownsite.panel.service"
    owner: root
    group: root
    mode: 0644

- name: "Install /etc/nginx/sites-enabled/{{ config.panel.domain }}"
  template:
    src: "{{ role_path }}/templates/nginx-domain.conf"
    dest: "/etc/nginx/sites-enabled/{{ config.panel.domain }}"
    owner: root
    group: root
    mode: 0644

- name: Add auth lines to pgsql hba config
  postgresql_pg_hba:
    dest: /etc/postgresql/13/main/pg_hba.conf
    contype: host
    source: "{{ item.address }}/32" 
    method: md5
    create: true
  with_items: "{{ config.database.allow_addresses }}"

- name: "Bind PSQL to localhost and {{ config.database.bind }}"
  lineinfile:
    path: /etc/postgresql/13/main/postgresql.conf
    regexp: '^listen_addresses '
    insertafter: '^#listen_addresses'
    line: "listen_addresses = 'localhost,{{ config.database.bind }}'"

- name: start postgresql
  service:
    name: postgresql
    state: restarted

- name: start nginx
  service:
    name: nginx
    state: restarted

- name: "Git clone from {{ config.panel.markdownsite_repo }}"
  git:
    repo: "{{ config.panel.markdownsite_repo }}"
    dest: /home/manager/markdownsite
    accept_hostkey: true
  become: true
  become_user: manager

## TODO ensure mds-panel gets dbc, and then replace this command.
- name: Import the database
  shell: mds-manager dbc < /home/manager/markdownsite/Panel-DB/etc/schema.sql > /home/manager/markdownsite/Panel-DB/etc/schema.log
  args:
    creates: /home/manager/markdownsite/Panel-DB/etc/schema.log
  become: true
  become_user: manager

# Start markdownsite.panel
- name: Start Markdownsite Panel
  service:
    name: markdownsite.panel
    state: started
    enabled: true
